modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GPL3"

[[mods]]
modId = "accelerateddecay"
version = "${version}"
displayName = "Accelerated Decay"
authors = "ErrorMikey"
description = '''
Speeds up the decay of leaves
'''
#logoFile = ""

[[dependencies.accelerateddecay]]
modId = "neoforge"
required = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "minecraft"
required = true
versionRange = "[1.20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "architectury"
required = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "accelerateddecay-common.mixins.json"

[[mixins]]
config = "accelerateddecay.mixins.json"
