modLoader = "javafml"
loaderVersion = "[3,)"
issueTrackerURL = "https://github.com/Nanite/AcceleratedDecay/issues"
license = "GPL3"

[[mods]]
modId = "accelerateddecay"
version = "${version}"
displayName = "Accelerated Decay"
authors = "ErrorMikey"
description = '''
Speeds up the decay of leaves
'''
#logoFile = ""

[[dependencies.accelerateddecay]]
modId = "neoforge"
required = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "minecraft"
required = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accelerateddecay]]
modId = "architectury"
required = true
versionRange = "[13.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "accelerateddecay-common.mixins.json"

[[mixins]]
config = "accelerateddecay.mixins.json"
