name: Release

on:
  push:
    tags:
      - "r/1.*/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK  17
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build & Publish
        run: ./gradlew build publish publishMods --no-daemon
        env:
          SAPS_TOKEN: ${{ secrets.SAPS_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURSE_TOKEN: ${{ secrets.CURSEFORGE_KEY }}
